models:
  - name: dim_listings_cleansed
    columns:
      - name: listing_id
        data_tests:
          - unique
          - not_null
      
      - name: host_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: 'host_id'
      
      - name: room_type
        data_tests:
          - accepted_values:
              arguments:
                values: ['Private room', 'Entire home/apt', 'Shared room', 'Hotel room']